In [1]:
import pandas as pd
import numpy as np
import itertools
import warnings
warnings.filterwarnings("ignore")

In [2]:
from clean_data import cleanData

In [11]:
# load csv and filter by productId
df = pd.read_csv(r'C:\Kenil Ramani\QB\GoalBot\CSV\dataset_v4.04.csv')

cd = cleanData(df)

In [12]:
# cd.filter_productsby(productId=165)

In [13]:
cd.filter_productsby(customerType='stockist')

,salesId,invoiceId,invoiceDate,quarter,month,year,day_of_week,day_of_month,day_of_year,week_of_year,...,contents,packingTypeId,divisionId,cityId,regionId,name,addressId,hqId,categoryId,chemistTypeId
30,385,DB-T-1106,2023-06-27,2,6,2023,3,27,178,26,...,GLIMEPIRIDE 1 MG + METFORMIN 1000 MG SR TAB,28,3,23.0,NaN,Gayatri Enterprises,56140.0,NaN,NaN,NaN
31,2277,DB-T-165,2023-04-12,2,4,2023,4,12,102,15,...,GLIMEPIRIDE 1 MG + METFORMIN 1000 MG SR TAB,28,3,23.0,NaN,Gayatri Enterprises,56140.0,NaN,NaN,NaN
32,37,DB-T-1006,2023-06-20,2,6,2023,3,20,171,25,...,GLIMEPIRIDE 1 MG + METFORMIN 1000 MG SR TAB,28,3,23.0,NaN,Gayatri Enterprises,56140.0,NaN,NaN,NaN
33,1507,DB-T-1427,2022-07-27,3,7,2022,4,27,208,31,...,GLIMEPIRIDE 1 MG + METFORMIN 1000 MG SR TAB,28,3,23.0,NaN,Gayatri Enterprises,56140.0,NaN,NaN,NaN
34,452,DB-T-1126,2022-07-04,3,7,2022,2,4,185,28,...,GLIMEPIRIDE 1 MG + METFORMIN 1000 MG SR TAB,28,3,23.0,NaN,Gayatri Enterprises,56140.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129167,55130,DB-T-3468,2024-11-29,4,11,2024,6,29,334,48,...,"Procapil, Capilia Longa, GHK-CU Peptide, and B...",48,1,484.0,9.0,A TO Z MEDICAL AGENCIES,88650.0,9.0,NaN,NaN
129168,8964,DB-T-3341,2023-12-09,4,12,2023,7,9,343,49,...,FUROATE 27.5MCG,45,3,77.0,1.0,Tollyjoy Distributor,56125.0,17.0,NaN,NaN
129169,8083,DB-T-3140,2023-11-25,4,11,2023,7,25,329,47,...,FUROATE 27.5MCG,45,3,77.0,1.0,Tollyjoy Distributor,56125.0,17.0,NaN,NaN
129170,3860,DB-T-2101,2023-09-04,3,9,2023,2,4,247,36,...,FUROATE 27.5MCG,45,3,77.0,1.0,Tollyjoy Distributor,56125.0,17.0,NaN,NaN
129171,1796,DB-T-151,2024-04-09,2,4,2024,3,9,100,15,...,FUROATE 27.5MCG,45,3,77.0,1.0,Tollyjoy Distributor,56125.0,17.0,NaN,NaN

In [14]:
cd.aggregate_sales(
    frequency='weekly_monday'
)

    invoiceDate      amount
0    2020-12-27   865007.62
1    2021-01-03  1540581.99
2    2021-01-10  1059954.02
3    2021-01-17  2079317.50
4    2021-01-24  1558613.19
..          ...         ...
210  2025-01-05  3333616.37
211  2025-01-12  2429043.77
212  2025-01-19  3230238.84
213  2025-01-26  3484237.99
214  2025-02-02  1055156.74

[215 rows x 2 columns]

In [15]:
cd.data_df

,salesId,invoiceId,invoiceDate,quarter,month,year,day_of_week,day_of_month,day_of_year,week_of_year,...,contents,packingTypeId,divisionId,cityId,regionId,name,addressId,hqId,categoryId,chemistTypeId
0,772,DB-T-1218,2022-07-11,3,7,2022,2,11,192,29,...,Amlodipine 5 mg Tab + Metoprolol Succinate 50 ...,28,3,22.0,NaN,STAR MEDICINES,83076.0,1.0,258.0,1.0
1,357,DB-T-11,2023-04-01,2,4,2023,7,1,91,13,...,Amlodipine 5 mg Tab + Metoprolol Succinate 50 ...,28,3,22.0,NaN,STAR MEDICINES,83076.0,1.0,258.0,1.0
2,655,DB-T-1185,2023-07-04,3,7,2023,3,4,185,27,...,Amlodipine 5 mg Tab + Metoprolol Succinate 50 ...,28,3,22.0,NaN,STAR MEDICINES,83076.0,1.0,258.0,1.0
3,2175,DB-T-162,2023-04-12,2,4,2023,4,12,102,15,...,Amlodipine 5 mg Tab + Metoprolol Succinate 50 ...,28,3,22.0,NaN,STAR MEDICINES,83076.0,1.0,258.0,1.0
4,432,DB-T-112,2024-04-05,2,4,2024,6,5,96,14,...,GLIMEPIRIDE 1 MG + METFORMIN 500 MG SR TAB,28,3,66.0,NaN,VARSHA PHARMACY,74567.0,45.0,259.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129171,1796,DB-T-151,2024-04-09,2,4,2024,3,9,100,15,...,FUROATE 27.5MCG,45,3,77.0,1.0,Tollyjoy Distributor,56125.0,17.0,NaN,NaN
129172,56160,DB-T-3650,2024-12-12,4,12,2024,5,12,347,50,...,Rabeprazole Sodium 20 mg Tab + Demperidone 30 ...,42,3,474.0,NaN,SHREEJI PHARMACY- NANDURBAR,93924.0,20.0,258.0,1.0
129173,56160,DB-T-3650,2024-12-12,4,12,2024,5,12,347,50,...,Levoceterizine 5mg,28,1,474.0,NaN,SHREEJI PHARMACY- NANDURBAR,93924.0,20.0,258.0,1.0
129174,56390,DB-T-3884,2024-12-30,4,12,2024,2,30,365,53,...,Bilastine 20 Mg Tab + Montelukast Sodium 10 mg...,28,3,22.0,NaN,DR.MADHAV PUROHIT,65694.0,8.0,NaN,NaN
129175,2838,DB-T-181,2024-04-11,2,4,2024,5,11,102,15,...,Sertaconazole 2% Cream (30 g.),36,1,22.0,NaN,DR.MADHAV PUROHIT,65694.0,8.0,NaN,NaN