In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

In [ ]:
df = pd.read_csv(r'C:\Kenil Ramani\QB\GoalBot\CSV\dataset_v1.27.csv')

In [19]:
df

,salesYear,salesMonth,InvoiceWeek,invoiceDate,salesDetails_id,billAmount,stockistId,chemistId,categoryId,hqId,...,free,rate,amount,productId,divisionId,product_name,packingTypeId,mrp.1,packingTypeId.1,packingTypeName
0,2021,1,1,1/1/2021,39119,457,NaN,1779.0,259.0,20.0,...,0,68.06,408.36,26,1,F-WASH SHAMPOO,38,216.0,38,100 ML
1,2021,1,1,1/1/2021,39247,45041,168.0,NaN,NaN,NaN,...,0,52.07,1562.10,168,3,BIO-ANXIT,28,85.5,28,10*10 TAB
2,2021,1,1,1/1/2021,39070,4530,NaN,5676.0,258.0,1.0,...,0,50.91,1527.30,248,3,TELEXA M 50,28,79.2,28,10*10 TAB
3,2021,1,1,1/1/2021,39436,3240,NaN,5225.0,259.0,1.0,...,0,57.86,1157.20,195,1,BIO-ITRA 100,42,180.0,42,10*10 CAP
4,2021,1,1,1/1/2021,39331,35465,93.0,NaN,NaN,17.0,...,30,40.50,0.00,254,3,VOLENT SP,28,75.6,28,10*10 TAB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129266,2025,2,6,2/4/2025,143531,129342,NaN,NaN,NaN,NaN,...,0,57.86,1157.20,172,3,BIO ANXIT NT,28,90.0,28,10*10 TAB
129267,2025,2,6,2/4/2025,143542,129342,NaN,NaN,NaN,NaN,...,0,104.14,3124.20,265,3,BIOXIGA -V,28,162.0,28,10*10 TAB
129268,2025,2,6,2/4/2025,143555,129342,NaN,NaN,NaN,NaN,...,0,48.59,2429.50,8,3,TELEXA H 40,28,69.3,28,10*10 TAB
129269,2025,2,6,2/4/2025,143513,98237,NaN,NaN,NaN,NaN,...,0,71.39,713.90,215,1,BIOKET SOAP,35,117.0,35,75 GM
129270,2025,2,6,2/4/2025,143564,36834,NaN,NaN,NaN,NaN,...,0,46.29,2314.50,166,3,BIOBETA-AM,28,72.0,28,10*10 TAB

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129271 entries, 0 to 129270
Data columns (total 26 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   salesYear        129271 non-null  int64
 1   salesMonth       129271 non-null  int64
 2   InvoiceWeek      129271 non-null  int64
 3   invoiceDate      129271 non-null  object
 4   salesDetails_id  129271 non-null  int64
 5   billAmount       129271 non-null  int64
 6   stockistId       102314 non-null  float64
 7   chemistId        25467 non-null   float64
 8   categoryId       20749 non-null   float64
 9   hqId             117350 non-null  float64
 10  hqName           117350 non-null  object
 11  regionId         117350 non-null  float64
 12  cityId           114418 non-null  float64
 13  cityName         114418 non-null  object
 14  mrp              129271 non-null  float64
 15  qty              129271 non-null  int64
 16  free             129271 non-null  int64
 17  rate             129271 non-null  float64
 18  amount           129271 non-null  float64
 19  productId        129271 non-null  int64
 20  divisionId       129271 non-null  int64
 21  product_name     129271 non-null  object
 22  packingTypeId    129271 non-null  int64
 23  mrp.1            129271 non-null  float64
 24  packingTypeId.1  129271 non-null  int64
 25  packingTypeName  129271 non-null  object
dtypes: float64(10), int64(11), object(5)
memory usage: 25.6+ MB

In [20]:
df.columns                  # 26 columns

Index(['salesYear', 'salesMonth', 'InvoiceWeek', 'invoiceDate',
       'salesDetails_id', 'billAmount', 'stockistId', 'chemistId',
       'categoryId', 'hqId', 'hqName', 'regionId', 'cityId', 'cityName', 'mrp',
       'qty', 'free', 'rate', 'amount', 'productId', 'divisionId',
       'product_name', 'packingTypeId', 'mrp.1', 'packingTypeId.1',
       'packingTypeName'],
      dtype='object')

In [21]:
# df = dff.drop(['salesYear', 'salesMonth', 'InvoiceWeek'],axis=1)
# df

In [22]:
df.describe()

,salesYear,salesMonth,InvoiceWeek,salesDetails_id,billAmount,stockistId,chemistId,categoryId,hqId,regionId,...,mrp,qty,free,rate,amount,productId,divisionId,packingTypeId,mrp.1,packingTypeId.1
count,129271.000000,129271.000000,129271.000000,129271.000000,1.292710e+05,102314.00000,25467.000000,20749.000000,117350.000000,117350.000000,...,129271.000000,129271.000000,129271.000000,129271.000000,1.292710e+05,129271.000000,129271.000000,129271.000000,129271.000000,129271.000000
mean,2022.714901,6.478661,26.587510,68848.141300,9.520661e+04,122.89629,3863.477559,261.421514,11.129374,2.074078,...,144.336072,52.661788,3.976344,91.963783,3.938218e+03,907.859628,2.366556,31.834835,151.733228,31.834835
std,1.162777,3.504869,15.364349,40516.692232,1.536354e+05,35.99730,2693.005262,6.554930,9.820709,4.087707,...,144.620769,75.677125,22.502041,563.255248,2.122293e+04,3457.401961,0.930400,5.730363,148.952436,5.730363
min,2021.000000,1.000000,1.000000,2.000000,-5.204000e+03,85.00000,649.000000,258.000000,1.000000,1.000000,...,23.400000,0.000000,0.000000,0.000000,0.000000e+00,1.000000,1.000000,1.000000,32.400000,1.000000
25%,2022.000000,3.000000,13.000000,34024.500000,1.599700e+04,97.00000,1758.000000,258.000000,4.000000,1.000000,...,72.000000,10.000000,0.000000,46.090000,9.258000e+02,167.000000,1.000000,28.000000,75.400000,28.000000
50%,2023.000000,7.000000,27.000000,68106.000000,4.639700e+04,105.00000,2928.000000,259.000000,8.000000,1.000000,...,99.000000,30.000000,0.000000,63.640000,2.082900e+03,213.000000,3.000000,28.000000,108.000000,28.000000
75%,2024.000000,10.000000,40.000000,101970.000000,1.191760e+05,168.00000,5473.000000,259.000000,17.000000,1.000000,...,162.000000,60.000000,0.000000,98.850000,4.339500e+03,241.000000,3.000000,36.000000,162.000000,36.000000
max,2025.000000,12.000000,53.000000,143626.000000,2.095248e+06,204.00000,11416.000000,283.000000,45.000000,32.000000,...,1260.000000,5030.000000,900.000000,200000.000000,7.200000e+06,17625.000000,3.000000,50.000000,1260.000000,50.000000

In [54]:
df['productId'].unique()
# ids = df["productId"].unique()
# sorted_ids = sorted([x for x in ids if pd.notnull(x)])
# sorted_ids

array([   26,   168,   248,   195,   254,   226,   283,    73,   218,
         234,   285,   249,    52,   233,   172,   216, 17249,   238,
           2,   223,   236,    75,   215,   205,   190,   169,   231,
         244,    70,   192,   206,     1,   212,   235,    13,   170,
           8,    35,   189,   165,   222,   181,   217,   255,   188,
         198,   252,   211,   185,   209,    27,   229,   203,   284,
         193,   220,   277,   167,   239,   241,   232,   280,    36,
         180,   221,   227,    46,   196,   253,    43,   194,   213,
          38,   173,   208,   224,   228,   177,   210,    71,   256,
         245,    42,    37, 17229,   271,   246,   261,   325,   294,
       17367,   201,   166,   260,   264,   230, 17366,   202,   263,
         278,   251,   250, 17368,   257,   265,    76,   270,   276,
          50,    48,   267,    79,   266,    11,   298,    16,    12,
          17, 17232, 17251, 17230, 17615, 17234, 17235, 17233, 17244,
       17253, 17370, 17369, 17362, 17560, 17553, 17558, 17616, 17614,
       17617, 17624, 17625])

In [39]:
df["invoiceDate"].unique()

array(['1/1/2021', '1/2/2021', '1/4/2021', ..., '2/1/2025', '2/3/2025',
       '2/4/2025'], dtype=object)

-No. of products - 138
-No. of stockists - 62
-No. of chemists - 324